rozmiar_ekranu: [800,600]

obrazy:
  ekran_powitalny: dane/ekran_powitalny.png
  tlo: dane/tlo.png
  blad_maly: dane/blad_maly.png
  blad_duzy: dane/blad_duzy.png
  aktywna_druzyna: dane/aktywna_druzyna.png

dzwieki:
  bledna_odpowiedz: dane/bledna_odpowiedz.ogg
  poprawna_odpowiedz: dane/poprawna_odpowiedz.ogg
  koniec_rundy: dane/koniec_rundy.ogg
  nowa_runda: dane/nowa_runda.ogg

muzyka:
  muzyka_na_start: dane/muzyka_na_start.ogg

czcionki:
  podstawowa:
    plik: dane/familiada.ttf
    rozmiar: 30
    kolor: [208,255,94]

  punkty_druzyn:
    plik: dane/familiada.ttf
    rozmiar: 60
    kolor: [208,255,94]

pytania: dane/pytania.yml

wspolrzedne:
  odpowiedzi:
    lp: [333,245]
    haslo: [373,245]
    punkty: [900,245]
    odstep: 50

  bledy:
    druzyna_0: [262,245]
    druzyna_1: [975,245]
    odstep: 150

  punkty:
    druzyna_0: [40,435]
    druzyna_1: [1110,435]
    punkty_przemnozone: [575,50]
    suma_napis: [770,690]
    suma_punkty: [900,690]

  nazwy_druzyn:
    druzyna_0: [20,955]
    druzyna_1: [905,955]

  aktywna_druzyna:
    druzyna_0: [-5,915]
    druzyna_1: [878,915]

teksty:
  suma: SUMA
  ukryte_haslo: ................................
  ukryte_punkty: __
