rozmiar_ekranu: [800,600]

obrazy:
  ekran_powitalny: dane/ekran_powitalny.png
  tlo: dane/tlo.png
  blad_maly: dane/blad_maly.png
  blad_duzy: dane/blad_duzy.png
  aktywna_druzyna: dane/aktywna_druzyna.png

dzwieki:
  bledna_odpowiedz: dane/bledna_odpowiedz.wav
  dobra_odpowiedz: dane/dobra_odpowiedz.wav

muzyka:
  muzyka_na_start: dane/muzyka_na_start.mp3

czcionki:
  podstawowa:
    plik: dane/familiada.ttf
    rozmiar: 40
    kolor: [208,255,94]

  punkty_druzyn:
    plik: dane/familiada.ttf
    rozmiar: 60
    kolor: [208,255,94]

pytania: dane/pytania.yml

wspolrzedne:
  odpowiedzi:
    lp: [285,100]
    haslo: [325,100]
    punkty: [920,100]
    odstep: 70

  bledy:
    druzyna_0: [210,100]
    druzyna_1: [1005,100]
    odstep: 150

  punkty:
    druzyna_0: [35,355]
    druzyna_1: [1110,355]
    suma_napis: [800,720]
    suma_punkty: [950,720]

  nazwy_druzyn:
    druzyna_0: [55,835]
    druzyna_1: [875,835]

  aktywna_druzyna:
    druzyna_0: [25,805]
    druzyna_1: [845,805]

teksty:
  suma: SUMA
  ukryte_haslo: .............................
  ukryte_punkty: __