grafika:
  ekran_powitalny: dane/ekran_powitalny.png
  tlo: dane/tlo.png

dzwieki:
  bledna_odpowiedz: dane/bledna_odpowiedz.wav
  dobra_odpowiedz: dane/dobra_odpowiedz.wav

muzyka:
  muzyka_na_start: dane/muzyka_na_start.mp3

czcionki:
  podstawowa:
    plik: dane/bpdots.squares.otf #dane/font.ttf
    rozmiar: 40

  punkty_druzyn:
    plik: dane/bpdots.squares.otf
    rozmiar: 60

  blad:
    plik: dane/bpdots.squares.otf
    rozmiar: 100

pytania: dane/pytania.yml
